apiVersion: "stable.agones.dev/v1alpha1"
kind: GameServer
metadata:
  name: gameserver-example
spec:
  ports:
  - name: default
    portPolicy: "dynamic"
    containerPort: 9410
  health:
    disabled: true
  template:
    spec:
      containers:
      - name: game
        image: bosakmaw/godot-agones:v0.7.0
